### ISSUE TITLE
Hi i got a error agian     java.lang.IndexOutOfBoundsException: null

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#12]
01:33:11.696 [RT-Ingest-auth_data] DEBUG i.i.server.rt.fetcher.Kafka08Fetcher - Illegal data: {"ydbpartion":"20161229","tablename":"auth_data","SOURCE_LINENO":"6579","ZIPNAME":"20161229","COLLECTION_EQUIPMENT_LONGITUDE":"119.6525360030066","CAPTURE_TIME":1482940891,"AREA_CODE":"330799","APPID":"","APP_SOFTWARE_NAME":"","COLLECTION_EQUIPMENT_ADRESS":"ZG5200161212_1010","COLLECTION_EQUIPMENT_MAC_LONG":68216227659,"ACCESS_AP_ENCRYPTION_TYPE":"","SSID_POSITION":"","PARSER_END_TIME":1483941482275,"X_COORDINATE":"","Y_COORDINATE":"","NETBAR_WACODE":"33070135100001","FILE_TIME":1483005406000,"FILETIME":"2016-12-29 17:56:46.000","NAME":"","ACCESS_AP_CHANNEL":"","NATIVE_PLACE":"","PARSER_START_TIME":1483941442234,"TYPE_NAME":"121212","PARSERENDTIME":"2017-01-09 13:58:02.275","TERMINAL_FIELDSTRENGTH":"0","CAPTURE_HMS":"00:01:31","MODEL":"","ATTRIBUTION":"","REGISTER_PHOTO":"","AUTH_ACCOUNT":"","MINUTE1":24715681,"INGESTTIME":"2017-01-09 13:52:38.095","COLLECTION_EQUIPMENT_MAC":"000FE201074B","COLLECTION_EQUIPMENT_NAME":"ZG520016121212_1010","CACHE_SSID":"","LOGNAME":"146-330701-1482941174-63113-WA_SOURCE_FJ_1001-0.bcp","IMEI_ESN_MEID":"","SESSIONID":"","TYPE_CODE":"skynet","ACCESS_AP_MAC":"","COLLECTION_EQUIPMENT_LATITUDE":"29.084175110946724","IMSI":"","MAC_LONG":240385446749710,"PARSERSTARTTIME":"2017-01-09 13:57:22.234","OS_NAME":"","PARSERTIME":324180,"COLLECTION_EQUIPMENTID":"728489494000FE201074B","CAPTURE_YMD":"2016-12-29","CERTIFICATE_CODE":"","APP_COMPANY_NAME":"","INGEST_TIME":1483941158095,"AREA_NAME":"江南区","CURRENT_PHOTO":"","AUTH_TYPE":"","IDENTIFICATION_TYPE":"","APP_VERSION":"","END_TIME":"","MAC":"DAA11929A60E","BRAND":""} 
java.lang.IndexOutOfBoundsException: null
	at java.nio.Buffer.checkIndex(Buffer.java:540) ~[na:1.8.0_40]
	at java.nio.HeapByteBuffer.get(HeapByteBuffer.java:139) ~[na:1.8.0_40]
	at io.indexr.util.UTF8JsonDeserializer.basicNumberCheck(UTF8JsonDeserializer.java:297) ~[indexr-common-0.1.0.jar:na]
	at io.indexr.util.UTF8JsonDeserializer.onNumber(UTF8JsonDeserializer.java:303) ~[indexr-common-0.1.0.jar:na]
	at io.indexr.util.UTF8JsonDeserializer.parse(UTF8JsonDeserializer.java:186) ~[indexr-common-0.1.0.jar:na]
	at io.indexr.segment.rt.UTF8JsonRowCreator.create(UTF8JsonRowCreator.java:148) ~[indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.UTF8JsonRowCreator.create(UTF8JsonRowCreator.java:136) ~[indexr-segment-0.1.0.jar:na]
	at io.indexr.server.rt.fetcher.Kafka08Fetcher.parseUTF8Row(Kafka08Fetcher.java:159) [indexr-server-0.1.0.jar:na]
	at io.indexr.server.rt.fetcher.Kafka08Fetcher.next(Kafka08Fetcher.java:148) [indexr-server-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeSegment.ingestRows(RealtimeSegment.java:276) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeSegment.realtimeIngest(RealtimeSegment.java:186) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable.doIngest(RealtimeTable.java:313) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable.ingest(RealtimeTable.java:255) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable.access$300(RealtimeTable.java:29) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable$1.lambda$run$13(RealtimeTable.java:178) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable$1$$Lambda$73/762015796.f(Unknown Source) [indexr-segment-0.1.0.jar:na]
	at io.indexr.util.Try.on(Try.java:38) [indexr-common-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable$1.run(RealtimeTable.java:177) [indexr-segment-0.1.0.jar:na]
	at io.indexr.util.DelayRepeatTask.runTaskInThread(DelayRepeatTask.java:39) [indexr-common-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable.lambda$startIngest$14(RealtimeTable.java:196) [indexr-segment-0.1.0.jar:na]
	at io.indexr.segment.rt.RealtimeTable$$Lambda$72/1479243425.run(Unknown Source) [indexr-segment-0.1.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

**Comment by flowbehappy** [comment]
@AisTop 

It looks like a value in this event is empty, and by the column schema, it represents a number, then the UTF8JsonDeserializer try to parse it into number will fail.  e.g.
column schema:
```
{"name": "a", "dataType": "int"},
{"name": "b", "dataType": "float"}
```
message:
```
{"a": "", "b": "0.2"}
```

We cannot parse an empty string into a number.

**Comment by AisTop** [comment]
think you . to avoid this ,I should turn  all of the column schema to String .   is this will solve my problem?

 I also have a question.   
Is  two or more than two  kafka topic  can be consume  by one table ?

**Comment by flowbehappy** [comment]
@AisTop 

My advice is if a field is empty, just don't put it in the event, it will use the column's default value. By default string column is empty string, number column is zero. 

And I don't suggest setting all column to string, because string is much more expensive than number, i.e. spend more cpu, ram, disk, especially on compression. And they cannot be calculated easily unless you explicitly cast then into number.

A table can consume multiple topics by setting kafka `topics` like this:

```json
        "fetcher": {
            "type": "kafka-0.8",
            "topics": ["topic0", "topic1"],
            "properties": {
                ....
                "group.id": "test_group"
            }
        }
```

I will put this into document later.
