### ISSUE TITLE
使用indexr的tools工具创建了table，但是在drill中查看不到。

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#2]
在indexr 的tools.sh 可以查看到有表：
![image](https://cloud.githubusercontent.com/assets/13936168/21607208/86bd91da-d1ef-11e6-866b-f7061277429c.png)
但是在drill 中查看不到？
![image](https://cloud.githubusercontent.com/assets/13936168/21607218/9f069c64-d1ef-11e6-8143-9608123332bd.png)
新创建的 test1 test2  test3 表查看不到。

**Comment by AisTop** [comment]
can‘t find table in drill console ，but find in tools.sh. just like the pictures describer

**Comment by flowbehappy** [comment]
Hi AisTop,

Can you check the errors in drillbit.log?
If you want to check more details, set the log level of "io.indexr" to "info" in $DRILL_HOME/conf/logback.xml.

**Comment by AisTop** [comment]
Hi flowbehappy  ,thinks you answer very much.
i changed the logback.xml   ,then i restart the drill and find some error in the drillbit.lgo 。
05:01:44.717 [main] WARN  org.reflections.Reflections - could not scan file /opt/baian/drill/jars/drill-indexr-storage-1.8.0.jar!/org/apache/drill/exec/store/indexr/IndexRRecordReaderByPack.class with scanner AnnotationScanner
org.reflections.ReflectionsException: could not create class file from IndexRRecordReaderByPack.class
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30) ~[reflections-0.9.8.jar:na]
	at org.reflections.Reflections.scan(Reflections.java:217) [reflections-0.9.8.jar:na]
	at org.reflections.Reflections.scan(Reflections.java:166) [reflections-0.9.8.jar:na]
	at org.reflections.Reflections.<init>(Reflections.java:94) [reflections-0.9.8.jar:na]
	at org.apache.drill.common.scanner.ClassPathScanner.scan(ClassPathScanner.java:402) [drill-common-1.9.0.jar:1.9.0]
	at org.apache.drill.common.scanner.RunTimeScan.fromPrescan(RunTimeScan.java:62) [drill-common-1.9.0.jar:1.9.0]
	at org.apache.drill.common.scanner.ClassPathScanner.fromPrescan(ClassPathScanner.java:452) [drill-common-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.expr.fn.HiveFunctionRegistry.<init>(HiveFunctionRegistry.java:67) [drill-storage-hive-core-1.9.0.jar:1.9.0]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422) [na:1.8.0_40]
	at org.apache.drill.exec.expr.fn.FunctionImplementationRegistry.<init>(FunctionImplementationRegistry.java:110) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.expr.fn.FunctionImplementationRegistry.<init>(FunctionImplementationRegistry.java:125) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.server.DrillbitContext.<init>(DrillbitContext.java:92) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.work.WorkManager.start(WorkManager.java:106) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.server.Drillbit.run(Drillbit.java:120) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:292) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.server.Drillbit.start(Drillbit.java:272) [drill-java-exec-1.9.0.jar:1.9.0]
	at org.apache.drill.exec.server.Drillbit.main(Drillbit.java:268) [drill-java-exec-1.9.0.jar:1.9.0]
Caused by: org.reflections.ReflectionsException: could not create class file from IndexRRecordReaderByPack.class
	at org.reflections.adapters.JavassistAdapter.createClassObject(JavassistAdapter.java:128) ~[reflections-0.9.8.jar:na]
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:118) ~[reflections-0.9.8.jar:na]
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:26) ~[reflections-0.9.8.jar:na]
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:27) ~[reflections-0.9.8.jar:na]
	... 19 common frames omitted
Caused by: java.io.IOException: invalid constant type: 18
	at javassist.bytecode.ConstPool.readOne(ConstPool.java:1090) ~[javassist-3.12.1.GA.jar:na]
	at javassist.bytecode.ConstPool.read(ConstPool.java:1033) ~[javassist-3.12.1.GA.jar:na]
	at javassist.bytecode.ConstPool.<init>(ConstPool.java:149) ~[javassist-3.12.1.GA.jar:na]
	at javassist.bytecode.ClassFile.read(ClassFile.java:737) ~[javassist-3.12.1.GA.jar:na]
	at javassist.bytecode.ClassFile.<init>(ClassFile.java:108) ~[javassist-3.12.1.GA.jar:na]
	at org.reflections.adapters.JavassistAdapter.createClassObject(JavassistAdapter.java:126) ~[reflections-0.9.8.jar:na]
	... 22 common frames omitted

**Comment by AisTop** [comment]
i can‘t solve this  by my self ,thinks you very much!

**Comment by flowbehappy** [comment]
Hi AisTop,

It looks like your jre does not support the class version. IndexR only support Java 1.8+. You should check your jre version.

**Comment by AisTop** [comment]
Hi flowbehappy    think you  , i find it.
it's my mistake ,because my test_exmple.json is not right ，kafka is not config 。so can‘t receive data from the kafka topic .
i try the sample  test.json  the content is   ;
{
    "schema":{
        "columns":
        [
            {"name": "date", "dataType": "int"},
            {"name": "d1", "dataType": "string"},
            {"name": "m1", "dataType": "int"},
            {"name": "m2", "dataType": "long"},
            {"name": "m3", "dataType": "float"},
            {"name": "m4", "dataType": "double"}
        ]
    }
}

create talbe 
./tools.sh -cmd settb -t hjjtest -c test_schem.json 
![image](https://cloud.githubusercontent.com/assets/13936168/21609236/3206c230-d1fc-11e6-836c-8c329badcb4a.png)

in the finally i succeess find the reson.

**Comment by flowbehappy** [comment]
I notice that you running Drill 1.9, and IndexR plugin is compiled under Drill 1.8, maybe that is the root cause. I will push a indexr-drill-1.9.0 later.

**Comment by flowbehappy** [comment]
Hi AisTop,
Happy to see you make it :)

**Comment by AisTop** [comment]
i will set the kafka topic and to check the issue. think you .
