### ISSUE TITLE
indexr+drill1.8.0  单机模式启动后一直报如下的错误。

### ISSUE THREAD

**Issue by AisTop** [shunfei/indexr#3]
my problem is after create table by index-tool  ，the drill console is continue get the error info 。
I use the json string to create the table  
{
    "schema":{
        "columns":
        [
            {"name": "date", "dataType": "int"},
            {"name": "d1", "dataType": "string"},
            {"name": "m1", "dataType": "int"},
            {"name": "m2", "dataType": "long"},
            {"name": "m3", "dataType": "float"},
            {"name": "m4", "dataType": "double"}
        ]
    }
}
and in the  drill console  could find table test  
![image](https://cloud.githubusercontent.com/assets/13936168/21633793/54d55f4c-d28d-11e6-9544-87b85d6dedde.png)

i don't know why this occur，place help me , think you。

22:43:52.383 [IndexR-Refresh-Notify] ERROR i.i.server.rt.RealtimeSegmentPool - 
java.lang.NoClassDefFoundError: org/apache/spark/unsafe/Platform
	at io.indexr.server.rt.RealtimeSegmentPool.refreshLocalRT(RealtimeSegmentPool.java:227) [indexr-server-0.1.0.jar:na]
	at io.indexr.server.rt.RealtimeSegmentPool$$Lambda$39/859028208.f(Unknown Source) ~[na:na]
	at io.indexr.util.Try.on(Try.java:12) ~[indexr-common-0.1.0.jar:na]
	at io.indexr.server.rt.RealtimeSegmentPool.refresh(RealtimeSegmentPool.java:198) [indexr-server-0.1.0.jar:na]
	at io.indexr.server.rt.RealtimeSegmentPool.lambda$new$4(RealtimeSegmentPool.java:103) [indexr-server-0.1.0.jar:na]
	at io.indexr.server.rt.RealtimeSegmentPool$$Lambda$42/1944303858.run(Unknown Source) [indexr-server-0.1.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

**Comment by flowbehappy** [comment]
Hi AisTop,

It looks like some jars, e.g. `spark-unsafe_2.10-1.6.0.jar`,  are missing. Please check your `$DRILL_HOME/jars/3rdparty/`.  Your should move all jars in `.../indexr/distribution/indexr-<version>/indexr-drill/jars/3rdparty` into this path.

**Comment by AisTop** [comment]
HI flowbehappy, think you.
but my  ../indexr/distribution/indexr-<version>/indexr-drill/jars/3rdparty   only has 4 jars  in the directory.
like:
![image](https://cloud.githubusercontent.com/assets/13936168/21670907/de02d3ce-d352-11e6-9e0e-cbb6920be639.png)

and compile the indexr source is success with no error.  what should i do .

**Comment by AisTop** [comment]
i found the spark-unsafe_2.10-1.6.0.jar  in the pom.xml   .
![image](https://cloud.githubusercontent.com/assets/13936168/21671236/f1ecc726-d354-11e6-8d71-17dc19633d2d.png)

should i copy all the jars into the $DRILL_HOME/jars/3rdparty/ path   of  the pom.xml . 
think you very much.

**Comment by flowbehappy** [comment]
@AisTop 

Maybe it is the problem of compilation scripts. You should check the compilation environment setting `indexr/script/env.sh`, and make sure `MAVEN_PATH` point to the correct path.

```
# local maven repo path
export MAVEN_PATH=~/.m2/repository
```

Maven downloads jars from remote repositories and stores them in local path. 
For `spark-unsafe_2.10-1.6.0.jar`, make sure you can find it at: `${MAVEN_PATH}/org/apache/spark/spark-unsafe_2.10/1.6.0/spark-unsafe_2.10-1.6.0.jar`

I will add the document for this.

**Comment by flowbehappy** [comment]
You can simply use 

```
export MAVEN_PATH=`mvn help:evaluate -Dexpression=settings.localRepository | grep -v '\[INFO\]'`
```

I have fix the issue with this commit: f723dee0590d55d0c05515ae78422277b6ef61cf

**Comment by AisTop** [comment]
i find the compile script describer the behavior cp action to copy the jars
![image](https://cloud.githubusercontent.com/assets/13936168/21672555/269d131e-d35e-11e6-8a0f-5efb07eea467.png)


so i could simply copy the jars to the target path ， i could solve this problem by this way。

**Comment by flowbehappy** [comment]
@AisTop 

Yes you can do that. 
But I suggest simply modify `MAVEN_PATH` following this commit f723dee0590d55d0c05515ae78422277b6ef61cf , in case of miss something. 😁

**Comment by AisTop** [comment]
think you  ，i write a  shell script to do this simple thing， to make sure   not miss anything 。 # @

-
